import type { Business, Category, Product } from './types';

export const INITIAL_BUSINESS: Business = {
  id: 'biz_001',
  tenantId: 'tenant_001',
  name: 'Burger Craft',
  slug: 'burger-craft',
  description: 'Hamburguesas artesanales premium con carne Angus smash, papas rústicas y salsas secretas.',
  logoUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=200&auto=format&fit=crop&q=80',
  bannerUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80',
  phone: '+56938980598',
  address: 'Av. Providencia 1240, Santiago',
  currency: 'CLP',
  currencySymbol: '$',
  primaryColor: '#f97316',
  whatsappOrders: true,
  isOpen: true,
  serviceSettings: {
    delivery: {
      enabledWeb: true,
      enabledPos: true,
      serviceFee: 1500,
      packagingFee: 500,
      minOrderAmount: 5000,
      freeDeliveryThreshold: 25000,
      avgDeliveryMinutes: 40,
      scheduledOrders: true,
      requireAddressDetails: true,
    },
    takeaway: {
      enabledWeb: true,
      enabledPos: true,
      avgPrepMinutes: 20,
    },
    dineIn: {
      enabledWeb: true,
      enabledPos: true,
    },
    tableDineIn: {
      enabledPos: true,
    },
    tips: {
      enabledWeb: true,
      enabledPos: true,
      suggestedPercentages: [5, 10, 15],
    },
  },
};


export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_01',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    name: 'Hamburguesas Smash',
    slug: 'hamburguesas-smash',
    description: 'Doble carne angus smash, pan brioche tostado y queso cheddar fundido.',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop&q=80',
    position: 1,
    isVisible: true,
  },
  {
    id: 'cat_02',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    name: 'Pizzas & Sandwiches',
    slug: 'pizzas-y-sandwiches',
    description: 'Pizzas a la piedra fermentadas 48h y sandwiches en pan artesanal.',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&auto=format&fit=crop&q=80',
    position: 2,
    isVisible: true,
  },
  {
    id: 'cat_03',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    name: 'Acompañamientos & Entradas',
    slug: 'acompanamientos-y-entradas',
    description: 'Papas rústicas, tequeños dorados y aros de cebolla crocantes.',
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=400&auto=format&fit=crop&q=80',
    position: 3,
    isVisible: true,
  },
  {
    id: 'cat_04',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    name: 'Bebidas & Cervezas',
    slug: 'bebidas-y-cervezas',
    description: 'Limonadas naturales, cervezas artesanales y gaseosas heladas.',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&auto=format&fit=crop&q=80',
    position: 4,
    isVisible: true,
  },
  {
    id: 'cat_05',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    name: 'Postres & Cafetería',
    slug: 'postres-y-cafeteria',
    description: 'Brownies con helado, tiramisú casero y cafés de especialidad.',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&auto=format&fit=crop&q=80',
    position: 5,
    isVisible: true,
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_01',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_01',
    name: 'Double Bacon Smash',
    description: '2 carnes smash de 90g, doble queso cheddar americano, tocino ahumado crocante y salsa especial.',
    price: 7990,
    compareAtPrice: 8990,
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-DBS-01',
    position: 1,
    isFeatured: true,
    isVisible: true,
    isAvailable: true,
    variants: [
      { id: 'v1', name: 'Simple (1 Smash)', priceDelta: -1500 },
      { id: 'v2', name: 'Doble (2 Smash)', priceDelta: 0, isDefault: true },
      { id: 'v3', name: 'Triple (3 Smash)', priceDelta: 2000 },
    ],
    modifiers: [
      { id: 'm1', groupName: 'Extras', name: 'Queso Cheddar Extra', price: 600, maxQuantity: 2 },
      { id: 'm2', groupName: 'Extras', name: 'Tiras de Tocino Extra', price: 990, maxQuantity: 2 },
      { id: 'm3', groupName: 'Extras', name: 'Pepinillos Dulces', price: 400, maxQuantity: 1 },
    ]
  },
  {
    id: 'prod_02',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_01',
    name: 'Truffle & Mushroom Burger',
    description: 'Doble smash, queso suizo, champiñones salteados a la mantequilla y mayonesa trufada.',
    price: 8490,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-TRUF-02',
    position: 2,
    isFeatured: true,
    isVisible: true,
    isAvailable: true,
    modifiers: [
      { id: 'm4', groupName: 'Extras', name: 'Huevo Frito de Campo', price: 800, maxQuantity: 1 },
      { id: 'm5', groupName: 'Extras', name: 'Cebolla Caramelizada', price: 600, maxQuantity: 1 },
    ]
  },
  {
    id: 'prod_03',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_01',
    name: 'BBQ Smokey Onion Burger',
    description: 'Doble carne Angus, aros de cebolla crujientes dentro, queso cheddar y salsa BBQ ahumada.',
    price: 8790,
    compareAtPrice: 9490,
    imageUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-BBQ-03',
    position: 3,
    isFeatured: true,
    isVisible: true,
    isAvailable: true,
    variants: [
      { id: 'v4', name: 'Doble Smash', priceDelta: 0, isDefault: true },
      { id: 'v5', name: 'Triple Smash', priceDelta: 1800 },
    ]
  },
  {
    id: 'prod_04',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_01',
    name: 'Crispy Chicken Supreme',
    description: 'Pechuga de pollo frita extracrocante, ensaladilla coleslaw agridulce y pepinillos.',
    price: 8990,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-CHK-04',
    position: 4,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_05',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_01',
    name: 'Triple Monster Bacon Smash',
    description: '3 carnes smash de 90g (270g carne), triple cheddar fundido y 4 tiras de tocino ahumado.',
    price: 10990,
    compareAtPrice: 12490,
    imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-MON-05',
    position: 5,
    isFeatured: true,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_06',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_02',
    name: 'Pizza Pepperoni Rústica Artesanal',
    description: 'Masa madre fermentada 48 horas, salsa pomodoro San Marzano, mozzarella fior di latte y pepperoni premium.',
    price: 13990,
    compareAtPrice: 15490,
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-PIZ-06',
    position: 6,
    isFeatured: true,
    isVisible: true,
    isAvailable: true,
    variants: [
      { id: 'v6', name: 'Mediana (6 porciones)', priceDelta: -2500 },
      { id: 'v7', name: 'Familiar (8 porciones)', priceDelta: 0, isDefault: true },
    ]
  },
  {
    id: 'prod_07',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_02',
    name: 'Pizza Cuatro Quesos al Horno',
    description: 'Mezcla perfecta de mozzarella, gorgonzola, parmesano reggiano y queso de cabra fundido.',
    price: 11490,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1573821663912-569905455b1c?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-PIZ-07',
    position: 7,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_08',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_02',
    name: 'Sandwich Mechada Italiana en Marraqueta',
    description: 'Carne mechada deshilachada a cocción lenta (6h), palta hass fresca, tomate y mayonesa casera.',
    price: 7890,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-SND-08',
    position: 8,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_09',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_03',
    name: 'Papas Rústicas con Cheddar & Bacon',
    description: 'Porción generosa de papas con corte artesanal, salsa cheddar tibia y lluvia de tocino crocante.',
    price: 4490,
    compareAtPrice: 4990,
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-PAP-09',
    position: 9,
    isFeatured: true,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_10',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_03',
    name: 'Aros de Cebolla Crujientes + BBQ',
    description: 'Aros de cebolla rebozados con panko japonés acompañados de salsa BBQ dulce.',
    price: 3890,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1639024471285-0afc3831f4a4?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-ARO-10',
    position: 10,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_11',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_03',
    name: 'Tequeños de Queso Fundido (6 un)',
    description: 'Masa fina y crujiente rellena de queso llanero fundido con salsa tártara de la casa.',
    price: 4890,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-TEQ-11',
    position: 11,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_12',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_04',
    name: 'Limonada Menta Jengibre (500ml)',
    description: 'Elaborada al momento con limones frescos exprimidos, hojas de menta orgánica y toque de jengibre.',
    price: 2990,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-LIM-12',
    position: 12,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_13',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_04',
    name: 'Cerveza IPA Artesanal 473cc',
    description: 'Cerveza con lúpulos cítricos americanos, amargor balanceado y notas tropicales (6.2° ABV).',
    price: 4200,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1608270192892-2632a84fb797?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-CER-13',
    position: 13,
    isFeatured: true,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_14',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_04',
    name: 'Cerveza Porter Tostada Artesanal',
    description: 'Cerveza negra con maltas tostadas, notas de café moca y cacao amargo (5.8° ABV).',
    price: 4300,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-CER-14',
    position: 14,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_15',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_05',
    name: 'Brownie Tibio con Helado de Vainilla',
    description: 'Brownie de chocolate belga con nueces, servido tibio con una bola de helado de vainilla.',
    price: 4190,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-POS-15',
    position: 15,
    isFeatured: true,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_16',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_05',
    name: 'Tiramisú Tradicional de la Casa',
    description: 'Bizcochos de soletilla bañados en espresso, crema mascarpone y cacao puro en polvo.',
    price: 4290,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-POS-16',
    position: 16,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_17',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_05',
    name: 'Capuchino Doble Moca',
    description: 'Doble espresso 100% arábica, leche vaporizada aterciopelada y sirope de chocolate oscuro.',
    price: 3100,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-CAF-17',
    position: 17,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  }
];
