import type { Business, Category, Product } from './types';

export const INITIAL_BUSINESS: Business = {
  id: 'biz_001',
  tenantId: 'tenant_001',
  name: 'Burger Craft & Co.',
  slug: 'burger-craft',
  description: 'Hamburguesas artesanales premium con carne Angus smash, papas rústicas y salsas secretas.',
  logoUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=200&auto=format&fit=crop&q=80',
  bannerUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80',
  phone: '+56912345678',
  address: 'Av. Providencia 1240, Santiago',
  currency: 'CLP',
  currencySymbol: '$',
  primaryColor: '#f97316',
  whatsappOrders: true,
  isOpen: true,
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_01',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    name: 'Hamburguesas Smash',
    slug: 'hamburguesas-smash',
    description: 'Doble carne angus smash, pan brioche tostado y queso cheddar fundido.',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop&q=80',
    position: 1,
    isVisible: true,
  },
  {
    id: 'cat_02',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    name: 'Acompañamientos',
    slug: 'acompanamientos',
    description: 'Papas fritas crujientes y aros de cebolla.',
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=400&auto=format&fit=crop&q=80',
    position: 2,
    isVisible: true,
  },
  {
    id: 'cat_03',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    name: 'Bebidas y Cervezas',
    slug: 'bebidas-y-cervezas',
    description: 'Gaseosas bien frías y cervezas artesanales.',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&auto=format&fit=crop&q=80',
    position: 3,
    isVisible: true,
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_01',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_01',
    name: 'Double Bacon Smash',
    description: '2 carnes smash de 90g, doble queso cheddar americano, tocino ahumado crocante y salsa especial.',
    price: 7990,
    compareAtPrice: 8990,
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-DBS-01',
    position: 1,
    isFeatured: true,
    isVisible: true,
    isAvailable: true,
    variants: [
      { id: 'v1', name: 'Simple (1 Smash)', priceDelta: -1500 },
      { id: 'v2', name: 'Doble (2 Smash)', priceDelta: 0, isDefault: true },
      { id: 'v3', name: 'Triple (3 Smash)', priceDelta: 2000 },
    ],
    modifiers: [
      { id: 'm1', groupName: 'Extras', name: 'Queso Cheddar Extra', price: 600, maxQuantity: 2 },
      { id: 'm2', groupName: 'Extras', name: 'Tiras de Tocino Extra', price: 990, maxQuantity: 2 },
      { id: 'm3', groupName: 'Extras', name: 'Pepinillos Dulces', price: 400, maxQuantity: 1 },
    ]
  },
  {
    id: 'prod_02',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_01',
    name: 'Truffle & Mushroom Burger',
    description: 'Doble smash, queso suizo, champiñones salteados a la mantequilla y mayonesa trufada.',
    price: 8490,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-TRUF-02',
    position: 2,
    isFeatured: true,
    isVisible: true,
    isAvailable: true,
    modifiers: [
      { id: 'm4', groupName: 'Extras', name: 'Huevo Frito de Campo', price: 800, maxQuantity: 1 },
      { id: 'm5', groupName: 'Extras', name: 'Cebolla Caramelizada', price: 600, maxQuantity: 1 },
    ]
  },
  {
    id: 'prod_03',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_02',
    name: 'Papas Rústicas con Cheddar & Bacon',
    description: 'Porción generosa de papas con corte artesanal, salsa cheddar tibia y lluvia de tocino.',
    price: 4490,
    compareAtPrice: 4990,
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-PAP-03',
    position: 3,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  },
  {
    id: 'prod_04',
    tenantId: 'tenant_001',
    businessId: 'biz_001',
    categoryId: 'cat_03',
    name: 'Limonada Menta Jengibre (500ml)',
    description: 'Elaborada con limones frescos, hojas de menta orgánica y toque de jengibre.',
    price: 2990,
    compareAtPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    sku: 'BC-LIM-04',
    position: 4,
    isFeatured: false,
    isVisible: true,
    isAvailable: true,
  }
];
