import type { OnboardingStage, OnboardingStep } from './types';

export const INITIAL_ONBOARDING_STAGES: OnboardingStage[] = [
  {
    id: 1,
    title: 'Etapa 1: Acciones clave',
    badge: '2/5',
    steps: [
      {
        id: 'step_account',
        stageId: 1,
        title: 'Crea tu cuenta',
        description: 'Ya completaste el registro y accediste al panel.',
        completed: true,
        actionUrl: '/admin',
        actionLabel: 'Ver Panel',
        iconName: 'UserCheck',
      },
      {
        id: 'step_first_product',
        stageId: 1,
        title: 'Crea o modifica tu primer producto',
        description: 'Comienza tu menú creando o modificando un plato o bebida con foto y precio.',
        completed: true,
        actionUrl: '/admin/products',
        actionLabel: 'Gestionar Menú',
        iconName: 'UtensilsCrossed',
      },
      {
        id: 'step_test_order_menu',
        stageId: 1,
        title: 'Haz un pedido de prueba con tu menú digital',
        description: 'Asegúrate de que todo funcione antes de comenzar a vender.',
        completed: false,
        actionUrl: '/menu/burger-craft',
        actionLabel: 'Abrir Menú Digital',
        iconName: 'Smartphone',
      },
      {
        id: 'step_whatsapp_chatbot',
        stageId: 1,
        title: 'Activa tu Chatbot de WhatsApp',
        description: 'Activa el asistente automático para responder dudas y gestionar pedidos automáticamente.',
        completed: false,
        actionUrl: '/admin/business#whatsapp',
        actionLabel: 'Configurar WhatsApp',
        iconName: 'Bot',
      },
      {
        id: 'step_test_order_pos',
        stageId: 1,
        title: 'Haz un pedido de prueba con el PDV',
        description: 'Ve cómo crear un pedido tú mismo desde el sistema.',
        completed: false,
        actionUrl: '/admin/kitchen',
        actionLabel: 'Ver Pedidos & PDV',
        iconName: 'Receipt',
      },
    ],
  },
  {
    id: 2,
    title: 'Etapa 2: Configuración esencial',
    badge: '0/5',
    steps: [
      {
        id: 'step_service_types',
        stageId: 2,
        title: 'Configurar tus tipos de servicio',
        description: 'Define si vendes en mesa, para llevar o delivery.',
        completed: false,
        actionUrl: '/admin/services',
        actionLabel: 'Configurar Servicios',
        iconName: 'Truck',
      },
      {
        id: 'step_payment_methods',
        stageId: 2,
        title: 'Configurar tus métodos de pago',
        description: 'Define si cobras en efectivo, transferencia o con link de pago.',
        completed: false,
        actionUrl: '/admin/business#payments',
        actionLabel: 'Métodos de Pago',
        iconName: 'CreditCard',
      },
      {
        id: 'step_schedules_info',
        stageId: 2,
        title: 'Configurar horarios e información general',
        description: 'Agregar horario de atención y datos del negocio.',
        completed: false,
        actionUrl: '/admin/business#hours',
        actionLabel: 'Horarios de Atención',
        iconName: 'Clock',
      },
      {
        id: 'step_address_location',
        stageId: 2,
        title: 'Configura la dirección',
        description: 'Muestra dónde estás y activa entregas o visibilidad local.',
        completed: false,
        actionUrl: '/admin/business#address',
        actionLabel: 'Ubicación Local',
        iconName: 'MapPin',
      },
      {
        id: 'step_google_my_business',
        stageId: 2,
        title: 'Vincular Google My Business',
        description: 'Muestra tu tienda en Google Maps y Google Search con el menú actualizado.',
        completed: false,
        actionUrl: '/admin/business#google',
        actionLabel: 'Conectar Google Maps',
        iconName: 'Globe',
      },
    ],
  },
  {
    id: 3,
    title: 'Etapa 3: Impulso al crecimiento',
    badge: '0/4',
    steps: [
      {
        id: 'step_loyalty_program',
        stageId: 3,
        title: 'Habilitar Programa de Fidelidad',
        description: 'Premia a los clientes frecuentes con recompensas automáticas.',
        completed: false,
        actionUrl: '/admin/business#loyalty',
        actionLabel: 'Configurar Fidelidad',
        iconName: 'Award',
      },
      {
        id: 'step_discount_coupon',
        stageId: 3,
        title: 'Crea un cupón de descuento',
        description: 'Atrae nuevos clientes o activa promociones por tiempo limitado.',
        completed: false,
        actionUrl: '/admin/products',
        actionLabel: 'Crear Cupón',
        iconName: 'Ticket',
      },
      {
        id: 'step_share_menu',
        stageId: 3,
        title: 'Comparte tu menú digital',
        description: 'Copia tu link y compártelo por redes sociales o WhatsApp.',
        completed: false,
        actionUrl: '/admin/qr',
        actionLabel: 'Códigos QR & Enlaces',
        iconName: 'Share2',
      },
      {
        id: 'step_add_team',
        stageId: 3,
        title: 'Añade tu equipo',
        description: 'Invita a otras personas para ayudarte a gestionar pedidos.',
        completed: false,
        actionUrl: '/admin/business#team',
        actionLabel: 'Invitar Equipo',
        iconName: 'Users',
      },
    ],
  },
  {
    id: 4,
    title: 'Etapa 4: Funciones avanzadas',
    badge: '0/3',
    steps: [
      {
        id: 'step_kds_prepared',
        stageId: 4,
        title: 'Marca un plato como preparado',
        description: 'Usa el sistema KDS para marcar pedidos listos en cocina.',
        completed: false,
        actionUrl: '/admin/kitchen',
        actionLabel: 'Abrir Cocina KDS',
        iconName: 'ChefHat',
      },
      {
        id: 'step_create_cashbox',
        stageId: 4,
        title: 'Crea una caja',
        description: 'Configura tu caja para manejar mejor tus ventas diarias.',
        completed: false,
        actionUrl: '/admin/business#cashbox',
        actionLabel: 'Configurar Caja',
        iconName: 'Wallet',
      },
      {
        id: 'step_stock_control',
        stageId: 4,
        title: 'Activa control de stock',
        description: 'Define cuánto stock tienes de cada producto y evita sobreventa.',
        completed: false,
        actionUrl: '/admin/products',
        actionLabel: 'Gestionar Stock',
        iconName: 'Boxes',
      },
    ],
  },
];
